// MindGraphSim - Material Library
// 31 materials across metals, minerals, and bio-elements

import { MaterialType, MaterialCategory, IntrinsicVector, ExtendedVector } from './types';

export interface MaterialDefinition {
  id: MaterialType;
  category: MaterialCategory;
  name: string;
  behavior: string;
  
  // Intrinsic 4D vector (N, U, C, S)
  vector: IntrinsicVector;
  scalar_weight: number;
  
  // Physics modifiers
  friction: number;
  stickiness: number;
  overload_threshold: number;
  
  // Light cone derivation
  cone_type: 'bacterial' | 'human' | 'extended';
  base_spatial_reach: number;
  base_temporal_reach: number;
  
  // Defaults for extended dimensions
  default_effort: number;
  default_feasibility: number;
  default_reach: number;
  default_strategic_fit: number;
  default_customer_value: number;
  default_time_to_impact: number;
  default_extendibility: number;
  default_imitability: number;
}

// ============================================
// METALS - Durable, structural, high-impact
// Cone type: human (structured, medium reach)
// ============================================

const METALS: MaterialDefinition[] = [
  {
    id: 'gold',
    category: 'metal',
    name: 'Gold',
    behavior: 'Foundational, high-impact idea anchor that attracts other objects',
    vector: { novelty: 0.8, utility: 0.9, connectivity: 0.9, stability: 0.95 },
    scalar_weight: 0.92,
    friction: 0.8,
    stickiness: 0.9,
    overload_threshold: 0.95,
    cone_type: 'human',
    base_spatial_reach: 12,
    base_temporal_reach: 8,
    default_effort: 0.3,
    default_feasibility: 0.7,
    default_reach: 0.9,
    default_strategic_fit: 0.85,
    default_customer_value: 0.9,
    default_time_to_impact: 0.4,
    default_extendibility: 0.8,
    default_imitability: 0.9,
  },
  {
    id: 'iron_metal',
    category: 'metal',
    name: 'Iron (Metal)',
    behavior: 'Practical, reliable, immediately applicable working ideas',
    vector: { novelty: 0.4, utility: 0.95, connectivity: 0.6, stability: 0.9 },
    scalar_weight: 0.85,
    friction: 0.7,
    stickiness: 0.5,
    overload_threshold: 0.9,
    cone_type: 'human',
    base_spatial_reach: 8,
    base_temporal_reach: 5,
    default_effort: 0.7,
    default_feasibility: 0.85,
    default_reach: 0.6,
    default_strategic_fit: 0.7,
    default_customer_value: 0.8,
    default_time_to_impact: 0.7,
    default_extendibility: 0.5,
    default_imitability: 0.4,
  },
  {
    id: 'nickel',
    category: 'metal',
    name: 'Nickel',
    behavior: 'Speculative, niche, unconventional connector ideas',
    vector: { novelty: 0.65, utility: 0.75, connectivity: 0.95, stability: 0.7 },
    scalar_weight: 0.65,
    friction: 0.4,
    stickiness: 0.7,
    overload_threshold: 0.75,
    cone_type: 'human',
    base_spatial_reach: 10,
    base_temporal_reach: 6,
    default_effort: 0.5,
    default_feasibility: 0.6,
    default_reach: 0.5,
    default_strategic_fit: 0.5,
    default_customer_value: 0.6,
    default_time_to_impact: 0.6,
    default_extendibility: 0.7,
    default_imitability: 0.5,
  },
  {
    id: 'copper',
    category: 'metal',
    name: 'Copper',
    behavior: 'Communication ideas that spread patterns efficiently between clusters',
    vector: { novelty: 0.55, utility: 0.7, connectivity: 0.96, stability: 0.6 },
    scalar_weight: 0.76,
    friction: 0.3,
    stickiness: 0.6,
    overload_threshold: 0.7,
    cone_type: 'human',
    base_spatial_reach: 15,
    base_temporal_reach: 4,
    default_effort: 0.6,
    default_feasibility: 0.75,
    default_reach: 0.8,
    default_strategic_fit: 0.6,
    default_customer_value: 0.7,
    default_time_to_impact: 0.8,
    default_extendibility: 0.6,
    default_imitability: 0.3,
  },
  {
    id: 'silver',
    category: 'metal',
    name: 'Silver',
    behavior: 'Reflective ideas that mirror and amplify nearby patterns',
    vector: { novelty: 0.7, utility: 0.8, connectivity: 0.85, stability: 0.75 },
    scalar_weight: 0.82,
    friction: 0.35,
    stickiness: 0.65,
    overload_threshold: 0.8,
    cone_type: 'human',
    base_spatial_reach: 11,
    base_temporal_reach: 6,
    default_effort: 0.45,
    default_feasibility: 0.7,
    default_reach: 0.75,
    default_strategic_fit: 0.7,
    default_customer_value: 0.8,
    default_time_to_impact: 0.6,
    default_extendibility: 0.7,
    default_imitability: 0.6,
  },
  {
    id: 'titanium',
    category: 'metal',
    name: 'Titanium',
    behavior: 'Withstands critique, resilient under pressure, lightweight strength',
    vector: { novelty: 0.6, utility: 0.85, connectivity: 0.5, stability: 0.98 },
    scalar_weight: 0.88,
    friction: 0.85,
    stickiness: 0.4,
    overload_threshold: 0.98,
    cone_type: 'human',
    base_spatial_reach: 7,
    base_temporal_reach: 10,
    default_effort: 0.4,
    default_feasibility: 0.8,
    default_reach: 0.6,
    default_strategic_fit: 0.8,
    default_customer_value: 0.75,
    default_time_to_impact: 0.5,
    default_extendibility: 0.7,
    default_imitability: 0.85,
  },
  {
    id: 'platinum',
    category: 'metal',
    name: 'Platinum',
    behavior: 'Rare catalyst ideas that enable transformations without being consumed',
    vector: { novelty: 0.85, utility: 0.85, connectivity: 0.7, stability: 0.9 },
    scalar_weight: 0.94,
    friction: 0.6,
    stickiness: 0.75,
    overload_threshold: 0.92,
    cone_type: 'human',
    base_spatial_reach: 9,
    base_temporal_reach: 12,
    default_effort: 0.25,
    default_feasibility: 0.6,
    default_reach: 0.7,
    default_strategic_fit: 0.9,
    default_customer_value: 0.85,
    default_time_to_impact: 0.35,
    default_extendibility: 0.9,
    default_imitability: 0.95,
  },
  {
    id: 'aluminum',
    category: 'metal',
    name: 'Aluminum',
    behavior: 'Lightweight, adaptable ideas that are easy to reshape',
    vector: { novelty: 0.5, utility: 0.75, connectivity: 0.7, stability: 0.6 },
    scalar_weight: 0.55,
    friction: 0.25,
    stickiness: 0.45,
    overload_threshold: 0.65,
    cone_type: 'human',
    base_spatial_reach: 10,
    base_temporal_reach: 4,
    default_effort: 0.85,
    default_feasibility: 0.9,
    default_reach: 0.7,
    default_strategic_fit: 0.55,
    default_customer_value: 0.65,
    default_time_to_impact: 0.85,
    default_extendibility: 0.8,
    default_imitability: 0.25,
  },
  {
    id: 'tungsten',
    category: 'metal',
    name: 'Tungsten',
    behavior: 'Extreme focus ideas that hold under very high load, increases local rigidity',
    vector: { novelty: 0.5, utility: 0.85, connectivity: 0.55, stability: 0.98 },
    scalar_weight: 0.86,
    friction: 0.95,
    stickiness: 0.3,
    overload_threshold: 0.98,
    cone_type: 'human',
    base_spatial_reach: 5,
    base_temporal_reach: 15,
    default_effort: 0.3,
    default_feasibility: 0.7,
    default_reach: 0.4,
    default_strategic_fit: 0.75,
    default_customer_value: 0.7,
    default_time_to_impact: 0.3,
    default_extendibility: 0.4,
    default_imitability: 0.9,
  },
  {
    id: 'chromium',
    category: 'metal',
    name: 'Chromium',
    behavior: 'Protective coating ideas that prevent corrosion of core concepts',
    vector: { novelty: 0.45, utility: 0.8, connectivity: 0.6, stability: 0.92 },
    scalar_weight: 0.78,
    friction: 0.7,
    stickiness: 0.55,
    overload_threshold: 0.88,
    cone_type: 'human',
    base_spatial_reach: 6,
    base_temporal_reach: 8,
    default_effort: 0.55,
    default_feasibility: 0.8,
    default_reach: 0.5,
    default_strategic_fit: 0.7,
    default_customer_value: 0.65,
    default_time_to_impact: 0.6,
    default_extendibility: 0.55,
    default_imitability: 0.7,
  },
];

// ============================================
// MINERALS - Contextual, atmospheric, pattern-holding
// Cone type: bacterial (local, crystalline)
// ============================================

const MINERALS: MaterialDefinition[] = [
  {
    id: 'quartz',
    category: 'mineral',
    name: 'Quartz',
    behavior: 'Transparent, clarifies relationships and focuses activation streams',
    vector: { novelty: 0.6, utility: 0.65, connectivity: 0.7, stability: 0.8 },
    scalar_weight: 0.77,
    friction: 0.5,
    stickiness: 0.4,
    overload_threshold: 0.8,
    cone_type: 'bacterial',
    base_spatial_reach: 4,
    base_temporal_reach: 3,
    default_effort: 0.6,
    default_feasibility: 0.7,
    default_reach: 0.5,
    default_strategic_fit: 0.6,
    default_customer_value: 0.6,
    default_time_to_impact: 0.65,
    default_extendibility: 0.6,
    default_imitability: 0.4,
  },
  {
    id: 'feldspar',
    category: 'mineral',
    name: 'Feldspar',
    behavior: 'Common foundation mineral that provides structural base for clusters',
    vector: { novelty: 0.35, utility: 0.7, connectivity: 0.65, stability: 0.85 },
    scalar_weight: 0.68,
    friction: 0.6,
    stickiness: 0.5,
    overload_threshold: 0.82,
    cone_type: 'bacterial',
    base_spatial_reach: 3,
    base_temporal_reach: 4,
    default_effort: 0.75,
    default_feasibility: 0.85,
    default_reach: 0.4,
    default_strategic_fit: 0.55,
    default_customer_value: 0.5,
    default_time_to_impact: 0.7,
    default_extendibility: 0.5,
    default_imitability: 0.3,
  },
  {
    id: 'mica',
    category: 'mineral',
    name: 'Mica',
    behavior: 'Layered ideas that can be peeled apart, flexible sheets of thought',
    vector: { novelty: 0.5, utility: 0.6, connectivity: 0.75, stability: 0.65 },
    scalar_weight: 0.62,
    friction: 0.2,
    stickiness: 0.35,
    overload_threshold: 0.6,
    cone_type: 'bacterial',
    base_spatial_reach: 5,
    base_temporal_reach: 2,
    default_effort: 0.8,
    default_feasibility: 0.8,
    default_reach: 0.45,
    default_strategic_fit: 0.5,
    default_customer_value: 0.55,
    default_time_to_impact: 0.8,
    default_extendibility: 0.7,
    default_imitability: 0.35,
  },
  {
    id: 'calcite',
    category: 'mineral',
    name: 'Calcite',
    behavior: 'Double-refracting ideas that show multiple perspectives simultaneously',
    vector: { novelty: 0.65, utility: 0.55, connectivity: 0.6, stability: 0.7 },
    scalar_weight: 0.65,
    friction: 0.45,
    stickiness: 0.4,
    overload_threshold: 0.68,
    cone_type: 'bacterial',
    base_spatial_reach: 4,
    base_temporal_reach: 3,
    default_effort: 0.65,
    default_feasibility: 0.65,
    default_reach: 0.5,
    default_strategic_fit: 0.55,
    default_customer_value: 0.6,
    default_time_to_impact: 0.6,
    default_extendibility: 0.65,
    default_imitability: 0.45,
  },
  {
    id: 'gypsum',
    category: 'mineral',
    name: 'Gypsum',
    behavior: 'Soft, moldable ideas that set into shape over time',
    vector: { novelty: 0.4, utility: 0.65, connectivity: 0.55, stability: 0.6 },
    scalar_weight: 0.55,
    friction: 0.3,
    stickiness: 0.6,
    overload_threshold: 0.55,
    cone_type: 'bacterial',
    base_spatial_reach: 3,
    base_temporal_reach: 2,
    default_effort: 0.9,
    default_feasibility: 0.9,
    default_reach: 0.35,
    default_strategic_fit: 0.45,
    default_customer_value: 0.5,
    default_time_to_impact: 0.85,
    default_extendibility: 0.55,
    default_imitability: 0.2,
  },
  {
    id: 'hematite',
    category: 'mineral',
    name: 'Hematite',
    behavior: 'Grounding ideas that anchor and stabilize volatile patterns',
    vector: { novelty: 0.35, utility: 0.75, connectivity: 0.5, stability: 0.92 },
    scalar_weight: 0.78,
    friction: 0.8,
    stickiness: 0.7,
    overload_threshold: 0.9,
    cone_type: 'bacterial',
    base_spatial_reach: 2,
    base_temporal_reach: 6,
    default_effort: 0.5,
    default_feasibility: 0.75,
    default_reach: 0.35,
    default_strategic_fit: 0.65,
    default_customer_value: 0.55,
    default_time_to_impact: 0.45,
    default_extendibility: 0.4,
    default_imitability: 0.6,
  },
  {
    id: 'fluorite',
    category: 'mineral',
    name: 'Fluorite',
    behavior: 'Fluorescent ideas that glow under certain conditions, reveal hidden patterns',
    vector: { novelty: 0.75, utility: 0.55, connectivity: 0.65, stability: 0.55 },
    scalar_weight: 0.64,
    friction: 0.35,
    stickiness: 0.45,
    overload_threshold: 0.6,
    cone_type: 'bacterial',
    base_spatial_reach: 5,
    base_temporal_reach: 2,
    default_effort: 0.55,
    default_feasibility: 0.55,
    default_reach: 0.6,
    default_strategic_fit: 0.5,
    default_customer_value: 0.65,
    default_time_to_impact: 0.7,
    default_extendibility: 0.7,
    default_imitability: 0.5,
  },
  {
    id: 'apatite',
    category: 'mineral',
    name: 'Apatite',
    behavior: 'Growth-oriented ideas that form the basis for larger structures',
    vector: { novelty: 0.55, utility: 0.7, connectivity: 0.7, stability: 0.7 },
    scalar_weight: 0.7,
    friction: 0.5,
    stickiness: 0.55,
    overload_threshold: 0.72,
    cone_type: 'bacterial',
    base_spatial_reach: 4,
    base_temporal_reach: 4,
    default_effort: 0.6,
    default_feasibility: 0.7,
    default_reach: 0.55,
    default_strategic_fit: 0.6,
    default_customer_value: 0.65,
    default_time_to_impact: 0.6,
    default_extendibility: 0.75,
    default_imitability: 0.45,
  },
  {
    id: 'tourmaline',
    category: 'mineral',
    name: 'Tourmaline',
    behavior: 'Challenges paradigms, refracts conventional thinking, piezoelectric',
    vector: { novelty: 0.85, utility: 0.5, connectivity: 0.7, stability: 0.6 },
    scalar_weight: 0.68,
    friction: 0.4,
    stickiness: 0.6,
    overload_threshold: 0.7,
    cone_type: 'bacterial',
    base_spatial_reach: 6,
    base_temporal_reach: 3,
    default_effort: 0.45,
    default_feasibility: 0.5,
    default_reach: 0.6,
    default_strategic_fit: 0.45,
    default_customer_value: 0.7,
    default_time_to_impact: 0.55,
    default_extendibility: 0.8,
    default_imitability: 0.6,
  },
  {
    id: 'garnet',
    category: 'mineral',
    name: 'Garnet',
    behavior: 'Dense, multifaceted ideas that cut through confusion',
    vector: { novelty: 0.6, utility: 0.75, connectivity: 0.6, stability: 0.85 },
    scalar_weight: 0.75,
    friction: 0.7,
    stickiness: 0.5,
    overload_threshold: 0.85,
    cone_type: 'bacterial',
    base_spatial_reach: 3,
    base_temporal_reach: 5,
    default_effort: 0.5,
    default_feasibility: 0.7,
    default_reach: 0.5,
    default_strategic_fit: 0.65,
    default_customer_value: 0.7,
    default_time_to_impact: 0.5,
    default_extendibility: 0.55,
    default_imitability: 0.55,
  },
];

// ============================================
// BIO-ELEMENTS - Embodied, process-oriented
// Cone type: extended (organic, far-reaching networks)
// ============================================

const BIO_ELEMENTS: MaterialDefinition[] = [
  {
    id: 'carbon',
    category: 'bio',
    name: 'Carbon',
    behavior: 'Versatile basis for complex structures, forms bonds in many configurations',
    vector: { novelty: 0.7, utility: 0.85, connectivity: 0.95, stability: 0.8 },
    scalar_weight: 0.89,
    friction: 0.3,
    stickiness: 0.85,
    overload_threshold: 0.75,
    cone_type: 'extended',
    base_spatial_reach: 20,
    base_temporal_reach: 10,
    default_effort: 0.5,
    default_feasibility: 0.8,
    default_reach: 0.7,
    default_strategic_fit: 0.75,
    default_customer_value: 0.8,
    default_time_to_impact: 0.6,
    default_extendibility: 0.95,
    default_imitability: 0.5,
  },
  {
    id: 'nitrogen',
    category: 'bio',
    name: 'Nitrogen',
    behavior: 'Accelerates processes, catalytic, essential for growth cycles',
    vector: { novelty: 0.6, utility: 0.75, connectivity: 0.8, stability: 0.5 },
    scalar_weight: 0.72,
    friction: 0.15,
    stickiness: 0.4,
    overload_threshold: 0.6,
    cone_type: 'extended',
    base_spatial_reach: 18,
    base_temporal_reach: 6,
    default_effort: 0.7,
    default_feasibility: 0.6,
    default_reach: 0.6,
    default_strategic_fit: 0.55,
    default_customer_value: 0.65,
    default_time_to_impact: 0.9,
    default_extendibility: 0.7,
    default_imitability: 0.3,
  },
  {
    id: 'oxygen',
    category: 'bio',
    name: 'Oxygen',
    behavior: 'Enables combustion of ideas, essential for energy release',
    vector: { novelty: 0.5, utility: 0.9, connectivity: 0.85, stability: 0.55 },
    scalar_weight: 0.75,
    friction: 0.1,
    stickiness: 0.35,
    overload_threshold: 0.55,
    cone_type: 'extended',
    base_spatial_reach: 25,
    base_temporal_reach: 4,
    default_effort: 0.8,
    default_feasibility: 0.85,
    default_reach: 0.8,
    default_strategic_fit: 0.6,
    default_customer_value: 0.75,
    default_time_to_impact: 0.95,
    default_extendibility: 0.6,
    default_imitability: 0.2,
  },
  {
    id: 'phosphorus',
    category: 'bio',
    name: 'Phosphorus',
    behavior: 'Energy storage and transfer, lights up under pressure',
    vector: { novelty: 0.65, utility: 0.8, connectivity: 0.75, stability: 0.6 },
    scalar_weight: 0.76,
    friction: 0.25,
    stickiness: 0.5,
    overload_threshold: 0.65,
    cone_type: 'extended',
    base_spatial_reach: 15,
    base_temporal_reach: 8,
    default_effort: 0.55,
    default_feasibility: 0.65,
    default_reach: 0.6,
    default_strategic_fit: 0.6,
    default_customer_value: 0.7,
    default_time_to_impact: 0.7,
    default_extendibility: 0.75,
    default_imitability: 0.45,
  },
  {
    id: 'sulfur',
    category: 'bio',
    name: 'Sulfur',
    behavior: 'Creates strong bonds, can be volatile, transformative',
    vector: { novelty: 0.7, utility: 0.65, connectivity: 0.7, stability: 0.5 },
    scalar_weight: 0.68,
    friction: 0.35,
    stickiness: 0.65,
    overload_threshold: 0.55,
    cone_type: 'extended',
    base_spatial_reach: 12,
    base_temporal_reach: 5,
    default_effort: 0.6,
    default_feasibility: 0.55,
    default_reach: 0.5,
    default_strategic_fit: 0.5,
    default_customer_value: 0.6,
    default_time_to_impact: 0.65,
    default_extendibility: 0.65,
    default_imitability: 0.4,
  },
  {
    id: 'calcium',
    category: 'bio',
    name: 'Calcium',
    behavior: 'Structural support, signaling, builds lasting frameworks',
    vector: { novelty: 0.4, utility: 0.85, connectivity: 0.65, stability: 0.9 },
    scalar_weight: 0.8,
    friction: 0.6,
    stickiness: 0.7,
    overload_threshold: 0.85,
    cone_type: 'extended',
    base_spatial_reach: 10,
    base_temporal_reach: 12,
    default_effort: 0.6,
    default_feasibility: 0.8,
    default_reach: 0.5,
    default_strategic_fit: 0.7,
    default_customer_value: 0.65,
    default_time_to_impact: 0.5,
    default_extendibility: 0.6,
    default_imitability: 0.5,
  },
  {
    id: 'magnesium',
    category: 'bio',
    name: 'Magnesium',
    behavior: 'Bright flare ideas, intense but brief, enables enzymatic processes',
    vector: { novelty: 0.6, utility: 0.7, connectivity: 0.75, stability: 0.55 },
    scalar_weight: 0.67,
    friction: 0.2,
    stickiness: 0.45,
    overload_threshold: 0.6,
    cone_type: 'extended',
    base_spatial_reach: 14,
    base_temporal_reach: 5,
    default_effort: 0.7,
    default_feasibility: 0.7,
    default_reach: 0.55,
    default_strategic_fit: 0.55,
    default_customer_value: 0.6,
    default_time_to_impact: 0.8,
    default_extendibility: 0.65,
    default_imitability: 0.35,
  },
  {
    id: 'potassium',
    category: 'bio',
    name: 'Potassium',
    behavior: 'Electrical signaling, rapid transmission, reactive',
    vector: { novelty: 0.55, utility: 0.75, connectivity: 0.85, stability: 0.45 },
    scalar_weight: 0.7,
    friction: 0.15,
    stickiness: 0.4,
    overload_threshold: 0.5,
    cone_type: 'extended',
    base_spatial_reach: 20,
    base_temporal_reach: 3,
    default_effort: 0.75,
    default_feasibility: 0.65,
    default_reach: 0.7,
    default_strategic_fit: 0.5,
    default_customer_value: 0.6,
    default_time_to_impact: 0.9,
    default_extendibility: 0.55,
    default_imitability: 0.25,
  },
  {
    id: 'sodium',
    category: 'bio',
    name: 'Sodium',
    behavior: 'Balances with potassium, essential for signal propagation',
    vector: { novelty: 0.5, utility: 0.8, connectivity: 0.8, stability: 0.5 },
    scalar_weight: 0.68,
    friction: 0.2,
    stickiness: 0.45,
    overload_threshold: 0.55,
    cone_type: 'extended',
    base_spatial_reach: 18,
    base_temporal_reach: 4,
    default_effort: 0.8,
    default_feasibility: 0.75,
    default_reach: 0.65,
    default_strategic_fit: 0.55,
    default_customer_value: 0.6,
    default_time_to_impact: 0.85,
    default_extendibility: 0.5,
    default_imitability: 0.2,
  },
  {
    id: 'iron_bio',
    category: 'bio',
    name: 'Iron (Bio)',
    behavior: 'Adaptive, binds and strengthens networks, oxygen carrier',
    vector: { novelty: 0.45, utility: 0.85, connectivity: 0.8, stability: 0.75 },
    scalar_weight: 0.8,
    friction: 0.4,
    stickiness: 0.6,
    overload_threshold: 0.78,
    cone_type: 'extended',
    base_spatial_reach: 15,
    base_temporal_reach: 8,
    default_effort: 0.6,
    default_feasibility: 0.75,
    default_reach: 0.6,
    default_strategic_fit: 0.65,
    default_customer_value: 0.7,
    default_time_to_impact: 0.6,
    default_extendibility: 0.7,
    default_imitability: 0.45,
  },
  {
    id: 'mycelium',
    category: 'bio',
    name: 'Mycelium',
    behavior: 'Slow underground patterns linking far nodes through quiet background growth',
    vector: { novelty: 0.7, utility: 0.6, connectivity: 0.98, stability: 0.75 },
    scalar_weight: 0.77,
    friction: 0.1,
    stickiness: 0.9,
    overload_threshold: 0.7,
    cone_type: 'extended',
    base_spatial_reach: 50,
    base_temporal_reach: 20,
    default_effort: 0.4,
    default_feasibility: 0.6,
    default_reach: 0.8,
    default_strategic_fit: 0.6,
    default_customer_value: 0.65,
    default_time_to_impact: 0.3,
    default_extendibility: 0.95,
    default_imitability: 0.7,
  },
];

// ============================================
// Combined Library
// ============================================

const ALL_MATERIALS: MaterialDefinition[] = [...METALS, ...MINERALS, ...BIO_ELEMENTS];

export class MaterialLibrary {
  private materials: Map<MaterialType, MaterialDefinition>;

  constructor() {
    this.materials = new Map(ALL_MATERIALS.map(m => [m.id, m]));
  }

  get(type: MaterialType): MaterialDefinition {
    return this.materials.get(type) ?? ALL_MATERIALS[0];
  }

  getByCategory(category: MaterialCategory): MaterialDefinition[] {
    return ALL_MATERIALS.filter(m => m.category === category);
  }

  list(): MaterialDefinition[] {
    return [...ALL_MATERIALS];
  }

  listByCategory(): Record<MaterialCategory, MaterialDefinition[]> {
    return {
      metal: METALS,
      mineral: MINERALS,
      bio: BIO_ELEMENTS,
    };
  }

  computeCompatibility(a: MaterialType, b: MaterialType): number {
    const ma = this.get(a);
    const mb = this.get(b);
    const va = ma.vector;
    const vb = mb.vector;

    // Dot product of normalized intrinsic vectors
    let dot = 0, magA = 0, magB = 0;
    const keys: (keyof IntrinsicVector)[] = ['novelty', 'utility', 'connectivity', 'stability'];
    for (const key of keys) {
      dot += va[key] * vb[key];
      magA += va[key] ** 2;
      magB += vb[key] ** 2;
    }
    return dot / (Math.sqrt(magA) * Math.sqrt(magB));
  }

  getDefaultExtendedVector(type: MaterialType): Partial<import('./types').ExtendedVector> {
    const m = this.get(type);
    return {
      effort: m.default_effort,
      feasibility: m.default_feasibility,
      reach: m.default_reach,
      strategic_fit: m.default_strategic_fit,
      customer_value: m.default_customer_value,
      time_to_impact: m.default_time_to_impact,
      extendibility: m.default_extendibility,
      imitability: m.default_imitability,
    };
  }
}

export const materialLibrary = new MaterialLibrary();
